export const SEARCH_USERS = "SEARCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_REPOS = "FETCH_USER_REPOS";
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const UPDATE_SELECTED_USER = 'UPDATE_SELECTED_USER';
export const CLEAR_SELECTED_USER = 'CLEAR_SELECTED_USER';